#!/usr/bin/env bash
# dispaly information about subdomain
# shellcheck disable=SC2086
sub_info () {
if [ $# -eq 1 ]
then
	subdomains='www lb-01 web-01 web-02'
else
	subdomains="$2"
fi
for i in $subdomains
do
	echo -n "The subdomain $i "
	dig "$i.$1" | awk 'NR == 14 {printf "is a %s record and points to %s\n", $4, $5}'
done
}
sub_info "$@"
