#!/usr/bin/env bash
# transfer file from client to server
# $1: path of file to transfer
# $2: ip of server
# $3: username for ssh to connect
# $4: path to ssh private key
if [ $# -lt 3 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
