#!/usr/bin/env bash
# configure nginx to return custom response header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location /redirect_me {
		return 301 https://google.com;
	}

	error_page 404 /404.html;
	location /404.html {
		internal;
	}

	add_header X-Served-By \$hostname;
}"
printf %s "$SERVER_CONFIG" > /etc/nginx/sites-available/default
sudo service nginx restart
