#!/usr/bin/env bash
# Loop from 1 to 10 to display "Best School"
# Except for 4th iteration, display "bad luck
# For 8th iteration, display "good luck"

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
